<?php
namespace frontend\modules\api;

class Module extends \yii\base\Module
{
    public $controllerNamespace = 'frontend\modules\api\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
